[package]
name = "termite"
version = "0.1.0"
authors = ["joey"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version = "0.4.8", features = ["std"]}
chrono = "0.4.11"
termcolor = "1.1.0"
